name = "OSSGH"
uuid = "135e50b6-a2ae-4e53-8c0b-0f5659f9d0de"
version = "0.1.0"

[deps]
Cascadia = "54eefc05-d75b-58de-a785-1a3403f0919f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Diana = "070d9d8b-17a7-5814-83fa-42438ba5c6e0"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LibPQ = "194296ae-ab2e-5f79-8cd4-7183a0a5a0d1"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
Diana = "0.2"
HTTP = "0.8"
JSON3 = "0.1"
LibPQ = "1"
Parameters = "0.12"
Tables = "0.2"
TimeZones = "1"
julia = "1"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter", "DataFrames", "Printf"]
